config/routes.rb
Rails.application.routes.draw do
# 一番上に上げたらうまく動いた、理由不明
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :follows, :followers
    end
  end
  resources :books do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  get 'home/about' => 'home#about'
  root to: 'home#top'
  get "search" => "search#search"

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
  	@user_or_book = params[:option]
  	@how_search = params[:choice]
  	if @user_or_book == "1"
    	@users = User.search(params[:search],@user_or_book, @how_search)
    else
     	@books = Book.search(params[:search],@user_or_book, @how_search)
    end
    render "search/search"
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.erb
<%= form_tag(search_path, :method => 'get') do %>
  <%= text_field_tag :search %>
  <%= select_tag(:option, options_for_select([["User","1"],["Book","2"]])) %>
  <%= select_tag(:choice, options_for_select([["完全一致","1"],["前方一致","2"],["後方一致","3"],["部分一致","4"]])) %>
  <%= submit_tag '検索', :nil => nil %>
<% end %>

app/views/search/search.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<% if @user_or_book == "1" %>
			<h2>Users search</h2>
			<!--users一覧 -->
			<%= render 'users/index', users: @users %>
			<!--users一覧 -->
			<% else %>
			<h2>Books search</h2>
			<!--books一覧 -->
			<%= render 'books/index', books: @books %>
			<!--books一覧 -->
			<% end %>
		</div>
	</div>
</div>