config/routes.rb
Rails.application.routes.draw do
# 一番上に上げたらうまく動いた、理由不明
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :follows, :followers
    end
  end
  resources :books do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  get 'home/about' => 'home#about'
  root to: 'home#top'
  get "search" => "search#search"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",foreign_key: "follower_id",dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",foreign_key: "followed_id",dependent:   :destroy
  has_many :follows, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def follows?(other_user)
    follows.include?(other_user)
  end

  def User.search(search, user_or_book, how_search)
    if user_or_book == "1"
      if how_search == "1"
        User.where(['name LIKE ?',"#{search}"])
      elsif how_search == "2"
        User.where(['name LIKE ?',"#{search}%"])
      elsif how_search == "3"
        User.where(['name LIKE ?',"%#{search}"])
      elsif how_search == "4"
        User.where(['name LIKE ?',"%#{search}%"])
      else
        User.all
      end
    end
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  def fulladdress
    self.prefecture_name + self.address_city + self.address_street
  end

# カラムは指定できるけど、XXXX.rb内で指定したメソッドでは無理っぽい？
# geocoderは結局使わなかった
# geocoded_by :address_city
# after_validation :geocode


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :baria_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
    @users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render action: :edit
  	end
  end

  def follows
    @user  = User.find(params[:id])
    @users = @user.follows
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
  end

  private

  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image, :postcode, :prefecture_code, :address_city, :address_street, :latitude, :longitude)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<!-- フォロー機能に関し、テーブル内でform_forは使わない方がいいみたいなのでlink_to使いたいけどフォロー外す際の変数がわからない(現状は問題なく動く) -->

<!--users一覧 -->
				<table class="table">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th colspan="4"></th>
						</tr>
					</thead>

					<tbody>
						<% users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50') %></td>
							<td><%= user.name%></td>
							<td><%= "フォロー数: #{user.follows.count}" %></td>
							<td><%= "フォロワー数: #{user.followers.count}" %></td>

							<% if user.id == current_user.id %>
								<td></td>
							<% else %>
								<% if current_user.follows?(user) %>
									<td>
										<!-- 渡す変数がわからない -->
										<!-- <%= link_to 'フォロー外す', relationships_path('わからない'), method: :delete %> -->
										<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }) do |f| %>
											<%= f.submit "フォロー外す", class: "btn btn-link" %>
										<% end %>
										</td>
								<% else %>
									<td>
										<!-- <%= link_to 'フォローする', relationships_path(followed_id:user.id), method: :POST %> -->
										<%= form_for(current_user.active_relationships.build) do |f| %>
											<div><%= hidden_field_tag :followed_id, user.id %></div>
											<%= f.submit "フォローする", class: "btn btn-link" %>
										<% end %>
									</td>
								<% end %>
							<% end %>
							<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			<!--users一覧 -->

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" , size:'100x100') %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

		<tr>
			<th>follows</th>
			<th><%= link_to "#{user.follows.count}", follows_user_url(user) %></th>
		</tr>

		<tr>
			<th>followers</th>
			<th><%= link_to "#{user.followers.count}", followers_user_url(user) %></th>
		</tr>

</table>

<div class="row">
	<% if user.id == current_user.id %>
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% else %>
		<% if current_user.follows?(user) %>
			<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),html: { method: :delete }) do |f| %>
 			<%= f.submit "フォロー外す", class: "btn btn-primary" %>
			<% end %>
		<% else %>
			<%= form_for(current_user.active_relationships.build) do |f| %>
				<div><%= hidden_field_tag :followed_id, @user.id %></div>
				<%= f.submit "フォローする", class: "btn btn-success" %>
			<% end %>
		<% end %>
	<% end %>
</div>

app/views/users/edit.html.erb
<div class="container">

<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<%= render 'layouts/errors', obj: @user %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :title %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

</div>

app/views/users/followers.html.erb
<div class="container">
	<h2>Follower Users</h2>
	<!--users一覧 -->
	<%= render 'index', users: @users %>
	<!--users一覧 -->
</div>

app/views/users/follows.html.erb
<div class="container">
	<h2>Follow Users</h2>
	<!--users一覧 -->
	<%= render 'index', users: @users %>
	<!--users一覧 -->
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
				<%= render 'users/profile', user: current_user %>
				<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>

		<div class="col-xs-9">
			<h2>Users</h2>
			<!--users一覧 -->
			<%= render 'index', users: @users %>
			<!--users一覧 -->
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">

	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>
			<!--同コントローラーのviewで表示ならusersは省略可　？ -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to (book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50' ) %>
							<% end %>
						</td>
						<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<td><%= "コメント数: #{book.book_comments.count}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

		</div>
	</div>
</div>
<!--books一覧 -->

<% if @user == current_user %>

<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['KEY']%>&callback=initMap" async></script>
<script type="text/javascript">
  var map;
  var marker;
  var geocoder;
  function initMap() {
    geocoder = new google.maps.Geocoder();
    geocoder.geocode({
    'address': '<%= @user.fulladdress %>' //住所
    }, function(results, status) {
      if (status === google.maps.GeocoderStatus.OK) {
      map = new google.maps.Map(document.getElementById('gmap'), {
        center: results[0].geometry.location,
        zoom: 17 //ズーム
     });
    marker = new google.maps.Marker({
    position: results[0].geometry.location,
    map: map
    });
    infoWindow = new google.maps.InfoWindow({
    content: '<h4>ツールチップのタイトル</h4>'
    });
    marker.addListener('click', function() {
      infoWindow.open(map, marker);
    });
    } else {
      alert(status);
    }
  });
}
</script>
<div id="gmap"></div>

<% end %>