config/routes.rb
Rails.application.routes.draw do
# 一番上に上げたらうまく動いた、理由不明
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :follows, :followers
    end
  end
  resources :books do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  get 'home/about' => 'home#about'
  root to: 'home#top'
  get "search" => "search#search"

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

  def Book.search(search, user_or_book, how_search)
    if user_or_book == "2"
      if how_search == "1"
        Book.where(['title LIKE ?',"#{search}"])
      elsif how_search == "2"
        Book.where(['title LIKE ?',"#{search}%"])
      elsif how_search == "3"
        Book.where(['title LIKE ?',"%#{search}"])
      elsif how_search == "4"
        Book.where(['title LIKE ?',"%#{search}%"])
      else
        Book.all
      end
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
  	@book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
      @user = current_user
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def delete
  	@book = Book.find(params[:id])
  	@book.destoy
  	redirect_to books_path, notice: "successfully delete book!"
  end

    def correct_user
      @book = Book.find(params[:id])
      @user = @book.user
      if current_user != @user
      redirect_to books_path
      end
    end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
					<td style="border:none;" >
						<%= link_to (book_comment.user) do %>
						<%= attachment_image_tag(book_comment.user, :profile_image, :fill, 34, 34, fallback: "no-image-mini.jpg", size:'34x34') %><br>
						<%= book_comment.user.name %>
						<% end %>
					</td>
					<td style="border:none;" ><%= book_comment.comment %></td>
					<% if book_comment.user == current_user %>
					<td style="border:none;" >
						<%= link_to "Destroy",book_book_comment_path(@book, book_comment[:id]), method: :delete, class: "btn-sm btn-danger" %>
					</td>
					<% end %>

app/views/books/_favorite.html.erb
						<td id="favorite_<%= book.id %>">
						<% if book.favorited_by?(current_user) %>
							<%= link_to book_favorites_path(book), method: :delete,  remote: true do %>
							<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							<%= book.favorites.count %>
							<% end %>
						<% else %>
							<%= link_to book_favorites_path(book), method: :post, remote: true do %>
							<i class="fa fa-heart-o" aria-hidden="true"></i>
							<%= book.favorites.count %>
							<% end %>
						<% end %>
						</td>

app/views/books/_form.html.erb
	<%= form_for [@book, @book_comment] do |f| %>
		<div class="flex">
		<%= f.text_area :comment, class: "col-xs-9 book_comment" %>
		<%= f.submit '送信' %>
		</div>
	<% end %>

app/views/books/_index.html.erb
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
				<% books.each do |book| %>
					<tr>
						<td>
							<%= link_to(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50') %>
							<% end %>
						</td>
						<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<!-- いいね 非同期通信-->
						<%= render 'books/favorite', book: book %>
						<!-- いいね 非同期通信-->
						<td><%= "コメント数: #{book.book_comments.count}" %></td>
					</tr>
				<% end %>
				</tbody>
			</table>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
  <h3><%= book.errors.count %>errors prohibited this book from being saved:</h3>
  <% book.errors.full_messages.each do |message| %>
<ul>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>
<% end %>

<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="container">

	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>

		<div class="col-xs-9">
			<h2>Books index</h2>
			<!--books一覧 -->
			<%= render 'books/index', books: @books %>
			<!--books一覧 -->
		</div>

	</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user:@user %>

		<h2>New book</h2>
		<%= render 'books/newform', book:Book.new %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

			<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50') %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<!-- いいね 非同期通信-->
					<%= render 'books/favorite', book: @book %>
					<!-- いいね 非同期通信-->
					<td id="book_count">
						<%= render 'book_comments/count', book: @book %>
					</td>
					<% if @book.user == current_user %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>

		<div id="book_comment_<%= @book.id %>">
			<!-- コメント 非同期通信-->
			<%= render 'book_comments/index', book: @book %>
			<!-- コメント 非同期通信-->
		</div>

	<%= form_with model:[@book, @book_comment] do |f| %>
		<div class="flex">
		<%= f.text_area :comment, class: "col-xs-9 book_comment" %>
		<%= f.submit '送信' %>
		</div>
	<% end %>

	</div>
</div>
</div>