config/routes.rb
Rails.application.routes.draw do
# 一番上に上げたらうまく動いた、理由不明
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :follows, :followers
    end
  end
  resources :books do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  get 'home/about' => 'home#about'
  root to: 'home#top'
  get "search" => "search#search"

end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' Home',user_path(current_user),class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' Users',users_path,class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' Books',books_path ,class: 'glyphicon glyphicon-book books'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'glyphicon glyphicon-log-out logout' %></li>
        <% else %>
          <li><%= link_to ' Home',root_path,class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' About',home_about_path,class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path,class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path ,class: 'glyphicon glyphicon-log-in sign_in'%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
<%= render 'layouts/header' %>
    <!--ヘッダーの記述-->

    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->
    </div>

    <% if user_signed_in? %>
    <div class='row'>
      <div class='col-xs-8 col-xs-offset-4'>
        <%= render 'search/form' %>
      </div>
    </div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>

  </body>
</html>